version: 2
jobs:
  build:
    docker:
      - image: precice/precice-ubuntu1604.home-develop
      - image: precicecoupling/openfoam

    working-directory: ~/openfoam-adapter

    steps:
      - checkout

        #- run:
        #    name: Updating dependencies
        #    command:  apt-get -qq update && apt-get -qq install
        #              software-properties-common
        #              wget apt-transport-https 
        #              libyaml-cpp-dev && 
        #              rm -rf /var/lib/apt/lists/* && 
        #              add-apt-repository "http://dl.openfoam.org/ubuntu dev" && 
        #              sh -c "wget -O - http://dl.openfoam.org/gpg.key | apt-key add -" && 
        #              add-apt-repository http://dl.openfoam.org/ubuntu && apt update && 
        #              apt-get -y install openfoam4 --no-install-recommends && 
        #              rm -rf /var/lib/apt/lists/*

      - run:
          name: Building adapter
          command: . /opt/openfoam4/etc/bashrc && ./Allwmake

      - run:
          name: Runnning simulation
          command: cd tutorials/CHT/flow-over-plate/buoyantPimpleFoam-laplacianFoam &&
                  . /opt/openfoam4/etc/bashrc && ./Allrun
