version: 2
jobs:
  build:
    docker:
      - image: precice/precice-ubuntu1604.home-develop

    steps:
      - checkout

      - run:
          name: Updating dependencies
          command:  apt-get -qq update && apt-get -qq install \
                    software-properties-common \
                    wget apt-transport-https \
                    libyaml-cpp-dev && \
                    add-apt-repository "http://dl.openfoam.org/ubuntu dev" && \
                    sh -c "wget -O - http://dl.openfoam.org/gpg.key | apt-key add -" && \
                    add-apt-repository http://dl.openfoam.org/ubuntu && apt update && \
                    apt-get -y install openfoam4 --no-install-recommends
      - run:
          name: Building adapter
          command:  cd openfoam-adapter &&  /opt/openfoam4/etc/bashrc && ./Allwmake

      - run:
          name: Runnning simulation
          command: cd /openfoam-adapter/tutorials/CHT/flow-over-plate/buoyantPimpleFoam-laplacianFoam && \ 
                  . /opt/openfoam4/etc/bashrc && ./Allwmake
